version: '3.9'

services:
  database:
    image: mariadb
    restart: always
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'

  discord-bot:
    build: .
    depends_on:
      - database
    environment:
      PREFIX: '.'
